import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
    faStar, faHeart, faBookmark, faFlag, faMedal, faTrophy, faCrown, faGem,
    faWandMagicSparkles, faTag, faHashtag,
    faHouse, faBuilding, faHotel, faWarehouse, faStore, faSchool, faChurch,
    faLandmark, faIndustry,
    faUser, faUsers, faUserPlus, faUserCheck, faBaby, faWheelchair,
    faPerson, faHandHoldingHeart,
    faStethoscope, faThermometer, faPills, faSyringe, faHeartPulse,
    faCross, faShieldHalved, faShield, faClipboardList, faClipboardCheck,
    faSun, faMoon, faCloud, faTree, faSeedling, faLeaf, faMountain, faWater,
    faUtensils, faMugHot, faKitchenSet, faWineGlass, faAppleWhole, faCarrot,
    faCar, faBus, faBicycle, faPlane, faShip, faLocationDot, faCompass, faRoute,
    faBed, faBath, faCouch, faLightbulb, faDoorOpen, faDoorClosed, faTv,
    faMusic, faGamepad, faBookOpen, faPalette, faCamera, faDumbbell, faMasksTheater,
    faPhone, faEnvelope, faCommentDots, faBell, faBullhorn,
    faClock, faCalendar, faStopwatch,
    faLock, faEye, faTriangleExclamation,
    faDollarSign, faCreditCard, faWallet, faReceipt, faPiggyBank,
    faWifi, faDesktop, faMobileScreenButton, faPrint, faGear, faWrench,
    faUmbrella, faSnowflake, faCloudRain, faWind,
    faScissors, faKey, faBolt, faFire, faPuzzlePiece,
    faCircleDot, faBriefcase, faGraduationCap,
    faTableColumns, faTableCells, faLayerGroup, faBox,
    faFaceSmile, faMagnifyingGlass, faXmark,
} from '@fortawesome/free-solid-svg-icons';

// Maps Lucide icon names (stored in DB) to Font Awesome icons for the public site
export const FA_ICON_MAP: Record<string, IconDefinition> = {
    // General
    Star: faStar,
    Heart: faHeart,
    Bookmark: faBookmark,
    Flag: faFlag,
    Award: faMedal,
    Trophy: faTrophy,
    Crown: faCrown,
    Gem: faGem,
    Sparkles: faWandMagicSparkles,
    Tag: faTag,
    Hash: faHashtag,
    // Buildings
    Home: faHouse,
    Building: faBuilding,
    Building2: faBuilding,
    Hotel: faHotel,
    Castle: faBuilding,
    Warehouse: faWarehouse,
    Store: faStore,
    School: faSchool,
    Church: faChurch,
    Landmark: faLandmark,
    Factory: faIndustry,
    // People
    User: faUser,
    Users: faUsers,
    UserPlus: faUserPlus,
    UserCheck: faUserCheck,
    Baby: faBaby,
    Accessibility: faWheelchair,
    PersonStanding: faPerson,
    HeartHandshake: faHandHoldingHeart,
    // Medical
    Stethoscope: faStethoscope,
    Thermometer: faThermometer,
    Pill: faPills,
    Syringe: faSyringe,
    Activity: faHeartPulse,
    HeartPulse: faHeartPulse,
    Cross: faCross,
    ShieldCheck: faShieldHalved,
    ShieldPlus: faShield,
    ClipboardList: faClipboardList,
    ClipboardCheck: faClipboardCheck,
    // Nature
    Sun: faSun,
    Moon: faMoon,
    Cloud: faCloud,
    TreePine: faTree,
    Flower2: faSeedling,
    Leaf: faLeaf,
    Mountain: faMountain,
    Waves: faWater,
    Sprout: faSeedling,
    Palmtree: faTree,
    // Food
    UtensilsCrossed: faUtensils,
    Coffee: faMugHot,
    CookingPot: faKitchenSet,
    Wine: faWineGlass,
    Apple: faAppleWhole,
    Salad: faCarrot,
    // Transport
    Car: faCar,
    Bus: faBus,
    Bike: faBicycle,
    Plane: faPlane,
    Ship: faShip,
    MapPin: faLocationDot,
    Navigation: faCompass,
    Route: faRoute,
    Compass: faCompass,
    // Furniture
    Bed: faBed,
    BedDouble: faBed,
    Bath: faBath,
    Sofa: faCouch,
    Lamp: faLightbulb,
    DoorOpen: faDoorOpen,
    DoorClosed: faDoorClosed,
    ArmchairIcon: faCouch,
    Tv: faTv,
    Refrigerator: faKitchenSet,
    // Activities
    Music: faMusic,
    Gamepad2: faGamepad,
    BookOpen: faBookOpen,
    Palette: faPalette,
    Camera: faCamera,
    Dumbbell: faDumbbell,
    Drama: faMasksTheater,
    PartyPopper: faStar,
    // Communication
    Phone: faPhone,
    Mail: faEnvelope,
    MessageCircle: faCommentDots,
    Bell: faBell,
    Megaphone: faBullhorn,
    // Time
    Clock: faClock,
    Calendar: faCalendar,
    Timer: faStopwatch,
    AlarmClock: faClock,
    // Safety
    Shield: faShield,
    Lock: faLock,
    Eye: faEye,
    AlertTriangle: faTriangleExclamation,
    // Finance
    DollarSign: faDollarSign,
    CreditCard: faCreditCard,
    Wallet: faWallet,
    Receipt: faReceipt,
    PiggyBank: faPiggyBank,
    // Technology
    Wifi: faWifi,
    Monitor: faDesktop,
    Smartphone: faMobileScreenButton,
    Printer: faPrint,
    Settings: faGear,
    Wrench: faWrench,
    // Weather
    Umbrella: faUmbrella,
    Snowflake: faSnowflake,
    CloudRain: faCloudRain,
    Wind: faWind,
    // Misc
    Scissors: faScissors,
    Key: faKey,
    Lightbulb: faLightbulb,
    Zap: faBolt,
    Flame: faFire,
    Puzzle: faPuzzlePiece,
    CircleDot: faCircleDot,
    SquareStack: faLayerGroup,
    Briefcase: faBriefcase,
    GraduationCap: faGraduationCap,
    Layout: faTableColumns,
    Grid: faTableCells,
    Layers: faLayerGroup,
    Box: faBox,
    Package: faBox,
    Smile: faFaceSmile,
    Search: faMagnifyingGlass,
    X: faXmark,
};
