import {
    Search, X, Smile, Layout, Grid, Layers, Box, Package, Tag, Hash,
    Star, Heart, Bookmark, Flag, Award, Trophy, Crown, Gem, Sparkles,
    Home, Building, Building2, Hotel, Castle, Warehouse, Store, School,
    Church, Landmark, Factory,
    User, Users, UserPlus, UserCheck, Baby, Accessibility,
    PersonStanding, HeartHandshake,
    Stethoscope, Thermometer, Pill, Syringe, Activity, HeartPulse,
    Cross, ShieldCheck, ShieldPlus, ClipboardList, ClipboardCheck,
    Sun, Moon, Cloud, TreePine, Flower2, Leaf, Mountain, Waves,
    Sprout, Palmtree,
    UtensilsCrossed, Coffee, CookingPot, Wine, Apple, Salad,
    Car, Bus, Bike, Plane, Ship, MapPin, Navigation, Route, Compass,
    Bed, BedDouble, Bath, Sofa, Lamp, DoorOpen, DoorClosed,
    ArmchairIcon, Tv, Refrigerator,
    Music, Gamepad2, BookOpen, Palette, Camera, Dumbbell,
    Drama, PartyPopper,
    Phone, Mail, MessageCircle, Bell, Megaphone,
    Clock, Calendar, Timer, AlarmClock,
    Shield, Lock, Eye, AlertTriangle,
    DollarSign, CreditCard, Wallet, Receipt, PiggyBank,
    Wifi, Monitor, Smartphone, Printer, Settings, Wrench,
    Umbrella, Snowflake, CloudRain, Wind,
    Scissors, Key, Lightbulb, Zap, Flame, Puzzle,
    CircleDot, SquareStack, Briefcase, GraduationCap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const ICON_LIST: { name: string; icon: LucideIcon }[] = [
    { name: "Star", icon: Star }, { name: "Heart", icon: Heart }, { name: "Bookmark", icon: Bookmark },
    { name: "Flag", icon: Flag }, { name: "Award", icon: Award }, { name: "Trophy", icon: Trophy },
    { name: "Crown", icon: Crown }, { name: "Gem", icon: Gem }, { name: "Sparkles", icon: Sparkles },
    { name: "Tag", icon: Tag }, { name: "Hash", icon: Hash },
    { name: "Home", icon: Home }, { name: "Building", icon: Building }, { name: "Building2", icon: Building2 },
    { name: "Hotel", icon: Hotel }, { name: "Castle", icon: Castle }, { name: "Warehouse", icon: Warehouse },
    { name: "Store", icon: Store }, { name: "School", icon: School }, { name: "Church", icon: Church },
    { name: "Landmark", icon: Landmark }, { name: "Factory", icon: Factory },
    { name: "User", icon: User }, { name: "Users", icon: Users }, { name: "UserPlus", icon: UserPlus },
    { name: "UserCheck", icon: UserCheck }, { name: "Baby", icon: Baby },
    { name: "Accessibility", icon: Accessibility },
    { name: "PersonStanding", icon: PersonStanding }, { name: "HeartHandshake", icon: HeartHandshake },
    { name: "Stethoscope", icon: Stethoscope }, { name: "Thermometer", icon: Thermometer },
    { name: "Pill", icon: Pill }, { name: "Syringe", icon: Syringe }, { name: "Activity", icon: Activity },
    { name: "HeartPulse", icon: HeartPulse }, { name: "Cross", icon: Cross },
    { name: "ShieldCheck", icon: ShieldCheck }, { name: "ShieldPlus", icon: ShieldPlus },
    { name: "ClipboardList", icon: ClipboardList }, { name: "ClipboardCheck", icon: ClipboardCheck },
    { name: "Sun", icon: Sun }, { name: "Moon", icon: Moon }, { name: "Cloud", icon: Cloud },
    { name: "TreePine", icon: TreePine }, { name: "Flower2", icon: Flower2 }, { name: "Leaf", icon: Leaf },
    { name: "Mountain", icon: Mountain }, { name: "Waves", icon: Waves },
    { name: "Sprout", icon: Sprout }, { name: "Palmtree", icon: Palmtree },
    { name: "UtensilsCrossed", icon: UtensilsCrossed }, { name: "Coffee", icon: Coffee },
    { name: "CookingPot", icon: CookingPot }, { name: "Wine", icon: Wine },
    { name: "Apple", icon: Apple }, { name: "Salad", icon: Salad },
    { name: "Car", icon: Car }, { name: "Bus", icon: Bus }, { name: "Bike", icon: Bike },
    { name: "Plane", icon: Plane }, { name: "Ship", icon: Ship }, { name: "MapPin", icon: MapPin },
    { name: "Navigation", icon: Navigation }, { name: "Route", icon: Route }, { name: "Compass", icon: Compass },
    { name: "Bed", icon: Bed }, { name: "BedDouble", icon: BedDouble }, { name: "Bath", icon: Bath },
    { name: "Sofa", icon: Sofa }, { name: "Lamp", icon: Lamp }, { name: "DoorOpen", icon: DoorOpen },
    { name: "DoorClosed", icon: DoorClosed }, { name: "Tv", icon: Tv }, { name: "Refrigerator", icon: Refrigerator },
    { name: "Music", icon: Music }, { name: "Gamepad2", icon: Gamepad2 }, { name: "BookOpen", icon: BookOpen },
    { name: "Palette", icon: Palette }, { name: "Camera", icon: Camera }, { name: "Dumbbell", icon: Dumbbell },
    { name: "Drama", icon: Drama }, { name: "PartyPopper", icon: PartyPopper },
    { name: "Phone", icon: Phone }, { name: "Mail", icon: Mail },
    { name: "MessageCircle", icon: MessageCircle }, { name: "Bell", icon: Bell },
    { name: "Megaphone", icon: Megaphone },
    { name: "Clock", icon: Clock }, { name: "Calendar", icon: Calendar },
    { name: "Timer", icon: Timer }, { name: "AlarmClock", icon: AlarmClock },
    { name: "Shield", icon: Shield }, { name: "Lock", icon: Lock },
    { name: "Eye", icon: Eye }, { name: "AlertTriangle", icon: AlertTriangle },
    { name: "DollarSign", icon: DollarSign }, { name: "CreditCard", icon: CreditCard },
    { name: "Wallet", icon: Wallet }, { name: "Receipt", icon: Receipt },
    { name: "PiggyBank", icon: PiggyBank },
    { name: "Wifi", icon: Wifi }, { name: "Monitor", icon: Monitor },
    { name: "Smartphone", icon: Smartphone }, { name: "Printer", icon: Printer },
    { name: "Settings", icon: Settings }, { name: "Wrench", icon: Wrench },
    { name: "Umbrella", icon: Umbrella }, { name: "Snowflake", icon: Snowflake },
    { name: "CloudRain", icon: CloudRain }, { name: "Wind", icon: Wind },
    { name: "Scissors", icon: Scissors }, { name: "Key", icon: Key },
    { name: "Lightbulb", icon: Lightbulb }, { name: "Zap", icon: Zap },
    { name: "Flame", icon: Flame }, { name: "Puzzle", icon: Puzzle },
    { name: "CircleDot", icon: CircleDot }, { name: "Briefcase", icon: Briefcase },
    { name: "GraduationCap", icon: GraduationCap },
    { name: "Layout", icon: Layout }, { name: "Grid", icon: Grid },
    { name: "Layers", icon: Layers }, { name: "Box", icon: Box },
    { name: "Package", icon: Package }, { name: "Smile", icon: Smile },
    { name: "Search", icon: Search }, { name: "X", icon: X },
    { name: "SquareStack", icon: SquareStack },
];

export const ICON_MAP: Record<string, LucideIcon> = {};
ICON_LIST.forEach(entry => { ICON_MAP[entry.name] = entry.icon; });
